
INSERT INTO song (author_id, category_id, reference, title) VALUES (1,3,'SALAMO25','SALAMO 25:Aminao Jehovah');
INSERT INTO verses (song_reference,lyrics, reference) VALUES ('SALAMO25', 'Aminao Jehovah ô,\nno anandratako ny fanahiko\nAndriamanitra ô!\nAndriamanitra ô!\nHianao no itokiako,\naoka tsy ho menatra aho\nHianao no itokiako,\naoka tsy ho menatra aho\nAoka tsy hifalian''\nny fahavaloko aho.\nAminao Jehovah ô,\nno anandratako ny fanahiko\nAndriamanitra ô!\nAndriamanitra ô!\nHianao no itokiako,\naoka tsy ho menatra aho\nHianao no itokiako,\naoka tsy ho menatra aho\nAoka tsy hifalian''\nny fahavaloko aho.\nEny, tsy hisy ho menatra\nizay rehetra miandry anao\nfa izay mivadika foana re,\nno ho menatra\nEny, tsy hisy ho menatra\nizay rehetra miandry anao\nfa izay mivadika foana re,\nno ho menatra\nAmpafantaro ny lalanao aho\nJehovah ô\nAmpianaro ny sitrakao aho\nAmpafantaro ny lalanao aho\nJehovah ô\nAmpianaro ny sitrakao aho\nAmpafantaro ny lalanao aho\nJehovah ô\nAmpianaro ny sitrakao aho', '1');
INSERT INTO song (author_id, category_id, reference, title) VALUES (1,3,'SALAMO103','SALAMO 103:Misaora');
INSERT INTO verses (song_reference,lyrics, reference) VALUES ('SALAMO103', 'Misaora, (Misaora)\nMisaora, (Misaora)\nMisaora an''i Jehovah,\nry fanahiko\nary izay (ary izay),\nrehetra (rehetra)\nary izay rehetra\nato anatiko\nMisaora ny Anarany Masina\nMisaora an''i Jehovah\n(Misaora Misaora) ry fanahiko\nary aza misy adinoinao\nny fitahiany rehetra\nizay mamela ny helokao\nizay manasitrana ny aretinao\nizay manavotra ny ainao\ntsy hidina\nany an davaka \nMisaora an''i Jehovah\n(Misaora Misaora) ny fanahiko\nary aza misy adinoinao\nny fitahiany rehetra\nizay mamela ny helokao\nizay manasitrana ny aretinao\nizay manavotra ny ainao\ntsy hidina\nany an davaka \nMisaora, (Misaora)\nMisaora, (Misaora)\nMisaora an''i Jehovah,\nry fanahiko\nary izay (ary izay),\nrehetra (rehetra)\nary izay rehetra\nato anatiko\nMisaora ny Anarany Masina', '1');
INSERT INTO song (author_id, category_id, reference, title) VALUES (1,3,'SALAMO133','SALAMO 133:Endrey');
INSERT INTO verses (song_reference,lyrics, reference) VALUES ('SALAMO133', 'Endrey, Endrey\nTsara sady\nmahafinatitra\nraha ny mpirahalhy\nno miara-monina\nEndrey, Endrey\nTsara sady\nmahafinatitra\nraha ny mpirahalhy\nno miara-monina\nTahaka ny diloilo\nTsara\nny diloilo tsara \namin''ny loha\nizay mitsororoka \namin''ny somotra\ndia ny somotr''i Arona\nizay mitsororoka\namin''ny moron-tongotr''\nakanjony;(Tahaka)\nTahaka ny ando any Hermona,\nizay milatsaka amin''ny\ntendrombohitra Ziona;\nFa voadidin''i Jehovah\nho eo ny fitahiana,\nDia fiainana\nfiainana ho mandrakizay\nTahaka ny diloilo\nTsara\nny diloilo tsara \namin''ny loha\nizay mitsororoka \namin''ny somotra\ndia ny somotr''i Arona\nizay mitsororoka\namin''ny moron-tongotr''\nakanjony;(Tahaka)\nTahaka ny ando any Hermona,\nizay milatsaka amin''ny\ntendrombohitra Ziona;\nFa voadidin''i Jehovah\nho eo ny fitahiana,\nDia fiainana\nfiainana ho mandrakizay\no! o! o! o!', '1');
INSERT INTO song (author_id, category_id, reference, title) VALUES (1,3,'SALAMO145','SALAMO 145:Hanandratra Anao aho');
INSERT INTO verses (song_reference,lyrics, reference) VALUES ('SALAMO145', 'Hanandratra anao aho,\nHanandratra anao aho,\nry Andriamanitro Mpanjaka ô! ô! ô!\nSy hankalaza ny anaranao,\nny anaranao mandrakizay doria.\nHankalaza anao\nisan''andro aho\nsy hidera ny anaranao (ny anaranao)\nsy hidera ny anaranao mandrakizay\ndoria, doria, doria, doria\nHanandratra anao aho,\nHanandratra anao aho,\nry Andriamanitro Mpanjaka ô! ô! ô!\nSy hankalaza ny anaranao,\nny anaranao mandrakizay doria.\nHankalaza anao\nisan''andro aho\nsy hidera ny anaranao (ny anaranao)\nsy hidera ny anaranao mandrakizay\ndoria, doria, doria, doria\nLehibe Jehovah\nka tokony hoderaina indrindra\nderaina indrindra\nAry tsy takatry ny saina\nny fahalebiazany\nny taranaka rehetra\nsamy hidera ny asanao\nsamy hidera ny asanao\namin''izay mandimby azy\nsy hanambara ny Asanao lehibe\nLehibe Jehovah\nka tokony hoderaina indrindra\nderaina indrindra\nAry tsy takatry ny saina\nny fahalebiazany\nny taranaka rehetra\nsamy hidera ny asanao\nsamy hidera ny asanao\namin''izay mandimby azy\nsy hanambara ny Asanao lehibe', '1');
